### ISSUE TITLE
Error with 0.2.4: Can't parse "https://www.w.org"

### ISSUE THREAD

**Issue by asselstine** [GoogleChromeLabs/native-url#15]
## Expected Behavior

`url.parse('https://www.w.org')` should yield:

```
{ slashes: true,
  host: 'www.e.org',
  hostname: 'www.e.org',
  protocol: 'https:',
  search: null,
  hash: null,
  query: null,
  pathname: '/',
  path: '/',
  auth: null,
  port: null,
  href: 'https://www.e.org/' }
```

## Actual Behavior

The above actually returns: 

But instead we get:

```
{ slashes: true,
  host: null,
  hostname: null,
  protocol: 'https:',
  search: null,
  hash: null,
  query: null,
  pathname: '/',
  path: '/',
  auth: null,
  port: null,
  href: 'https:///' }
```

## Steps to Reproduce the Problem

Try parsing a url whose hostname begins with 'www.w':

Fails:
`url.parse('https://www.w.org')` 

Succeeds:
`url.parse('https://w.org')` 

## Specifications

- Version: 0.2.4

**Comment by Timer** [comment]
This should also be tested with https://www.wikipedia.org/

**Comment by janicklas-ralph** [comment]
Thanks for posting this. This should be fixed.
