### ISSUE TITLE
Incorrectly parsing ?filter=size:10

### ISSUE THREAD

**Issue by bmathews** [GoogleChromeLabs/native-url#24]
## Expected Behavior
`parse('?filter=size:10')` should return correct values, like node's url.parse:

![image](https://user-images.githubusercontent.com/848347/78412232-7a5bce00-75c7-11ea-87ba-29ddc92cf003.png)

## Actual Behavior

Incorrectly appends `00` to end of url after parsing:
![image](https://user-images.githubusercontent.com/848347/78412078-edb11000-75c6-11ea-9a32-8226c2b74cc6.png)

This seems to be related to the colon, which should arguably be encoded. 

## Steps to Reproduce the Problem

`parse('?filter=size:10')`

## Specifications

- Version: 0.2.6

**Comment by janicklas-ralph** [comment]
Fixed in `0.3.1`

**Comment by bmathews** [comment]
Thanks @janicklas-ralph !
