### ISSUE TITLE
TS types

### ISSUE THREAD

**Issue by Toxicable** [GoogleChromeLabs/native-url#5]
Hey team, i'd like to use this package directly as a so I don't have to do a build time replacement of `url` -> `native-url`, but we appear to be missing Typings.
Is it in scope of this project to support direct usage of this lib? if so could we add in some typings?

One way to do it would be  to depend on the ttypings from `@types/node` and use those

**Comment by developit** [comment]
Hi @Toxicable. I like the idea of re-exporting the Node typings from here. If you think that can work, want to PR it? Cheers!
